all:
  children:
    test:
      hosts:
        test1: {ansible_host: "192.168.122.10", ansible_user: "gitlab-runner-ansible", ansible_connection: "ssh", ansible_port: 222}
        test2: {ansible_host: "192.168.122.11", ansible_user: "gitlab-runner-ansible", ansible_connection: "ssh", ansible_port: 222}
